# Generated by Django 5.0.3 on 2024-08-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('about_txt', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(default='bg.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=60)),
                ('dp', models.ImageField(default='staff.png', upload_to='')),
                ('position', models.CharField(max_length=75)),
                ('whatsapp', models.CharField(blank=True, max_length=1024)),
                ('instagram', models.CharField(blank=True, max_length=1024)),
                ('linkedIn', models.CharField(blank=True, max_length=1024)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon_name', models.CharField(max_length=105)),
                ('culture_name', models.CharField(max_length=255)),
                ('culture_txt', models.CharField(max_length=750)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Pillars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon_name', models.CharField(max_length=105)),
                ('pillar_name', models.CharField(max_length=255)),
                ('pillar_txt', models.CharField(max_length=750)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('img', models.ImageField(default='img.png', upload_to='')),
                ('description', models.CharField(max_length=1024)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
    ]
